---

- name: Install requirements
  become: false
  connection: local
  hosts: all
  gather_facts: false
  run_once: true
  check_mode: false
  environment:
    GIT_SSH_COMMAND: "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"
  tags:
  - always
  pre_tasks:
  - name: Update local ansible collections
    delegate_to: localhost
    ansible.builtin.command: ansible-galaxy collection install -r requirements.yml --force
  - name: Update local ansible roles
    delegate_to: localhost
    ansible.builtin.command: ansible-galaxy role install -r requirements.yml --force
